# Generated by Django 4.2.5 on 2024-10-08 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, max_length=255, null=True)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='')),
                ('order', models.IntegerField(blank=True, null=True)),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Act',
            fields=[
                ('template_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='template.template')),
                ('image', models.ImageField(blank=True, null=True, upload_to='act_images')),
                ('file', models.FileField(blank=True, null=True, upload_to='act_files')),
                ('text_input', models.TextField(blank=True, max_length=2056, null=True)),
            ],
            bases=('template.template',),
        ),
        migrations.CreateModel(
            name='Engage',
            fields=[
                ('template_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='template.template')),
                ('big_idea', models.TextField(blank=True, max_length=2056, null=True)),
                ('essential_question', models.TextField(blank=True, max_length=2056, null=True)),
                ('challenge', models.TextField(blank=True, max_length=2056, null=True)),
            ],
            bases=('template.template',),
        ),
        migrations.CreateModel(
            name='Investigate',
            fields=[
                ('template_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='template.template')),
                ('guiding_question', models.TextField(blank=True, max_length=2056, null=True)),
                ('guiding_resource', models.TextField(blank=True, max_length=2056, null=True)),
                ('guiding_activity', models.TextField(blank=True, max_length=2056, null=True)),
                ('result', models.TextField(blank=True, max_length=2056, null=True)),
                ('date_start', models.CharField(blank=True, max_length=255, null=True)),
                ('date_end', models.CharField(blank=True, max_length=255, null=True)),
            ],
            bases=('template.template',),
        ),
    ]
