# Generated by Django 4.2.5 on 2024-10-08 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('order', models.IntegerField()),
                ('content', models.TextField(default='Sem conteudo')),
                ('type_content', models.CharField(default='Sem conteudo', max_length=255)),
            ],
        ),
    ]
